name: Package release
on:
  release:
    types: [published]

jobs:
  build:
    name: Package build
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v3
      - name: Node.js 18 (LTS) setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "`yarn` installation"
        run: npm install -g yarn
      - name: Dependencies installation
        run: yarn ci
      - name: Type check
        run: yarn check:types
      - name: Style check
        run: yarn lint:prod
      - name: Project build
        run: yarn build
      - name: Artifact generation
        run: yarn pack
      - name: Artifact unpack
        shell: bash
        run: |
          PACKAGE_VERSION=`node -e "console.log(require('./package.json').version);"`
          PACKAGE_NAME="byloth-exceptions-v${PACKAGE_VERSION}.tgz"
          tar -xzvf "${PACKAGE_NAME}" -C "."

      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: byloth-exceptions
          path: package

  npm-release:
    name: Package release on NPM
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Node.js 18 (LTS) setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: byloth-exceptions

      - name: Package release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  gpr-release:
    name: Package release on GPR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Node.js 18 (LTS) setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: byloth-exceptions

      - name: Package release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
