name: NPM release
on:
  release:
    types: [published]

jobs:
  artifact-build:
    name: Artifact
    uses: ./.github/workflows/template-build.yml

  publish-npm:
    name: NPM
    needs: artifact-build
    uses: ./.github/workflows/template-publish.yml
    with:
      auth-token: ${{ secrets.NPM_TOKEN }}
